enum actionTypes {
  ADD_INGREDIENT = 'ADD_INGREDIENT',
  REMOVE_INGREDIENT = 'REMOVE_INGREDIENT',
  INIT_INGREDIENTS = 'INIT_INGREDIENTS',
  FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED',
  ORDERING = 'ORDERING',
  NOT_ORDERING = 'NOT_ORDERING',
  SEND_ORDER_START = 'SEND_ORDER_START',
  SEND_ORDER_SUCCESSFUL = 'SEND_ORDER_SUCCESSFUL',
  SEND_ORDER_FAILED = 'SEND_ORDER_FAILED',
  INIT_ORDER = 'INIT_ORDER',
  AUTH_START = 'AUTH_START',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_FAIL = 'AUTH_FAIL',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH = 'AUTH',
}

export default actionTypes;
